name: publish-mkdocs
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pipx install poetry
      - run: poetry install --only docs
      - run: poetry run mkdocs gh-deploy --force
